dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
networks:
  rinkeby:
    price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify_flag: True
  mainnet-fork-dev:
    price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'  
    verify_flag: False
  ganache-local:
    verify_flag: False
  development:
    verify_flag: False
  
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
